INSERT INTO APP.ARTICULOS (PRECIO, NOMBRE, DESCRIPCION) 
	VALUES (1000, 'Pro i7 3.2', 'Procesador Intel i7 a 3.2 GigaHertz');
	
INSERT INTO APP.ARTICULOS (PRECIO, NOMBRE, DESCRIPCION) 
	VALUES (1500, 'RAM DDR3 ADATA 2GB', 'Memoría RAM DD3 AData de 2 GB ');
	
INSERT INTO APP.ARTICULOS (PRECIO, NOMBRE, DESCRIPCION) 
	VALUES (500, 'Giga Mother i7', 'MotherBoard para procesador i7');
	
INSERT INTO APP.CLIENTE (NOMBRE, ULTIMA_ACTIVIDAD, RFC, ID_USUARIO) 
	VALUES ('PUBLICO EN GENERAL', CURRENT_TIMESTAMP, 'ABCDE123456XYZ', NULL);
